### ISSUE TITLE
Parsing "1/0" as Ratio panics

### ISSUE THREAD

**Issue by murarth** [rust-num/num#122]
It seems to me it should return an error. `ParseRatioError` would need to be changed into an enum. I can make a PR if this change is acceptable.

**Comment by cuviper** [comment]
I'd say take a cue from `ParseIntError` and leave it as an opaque struct.

```
pub struct ParseIntError { kind: IntErrorKind }
```

**Comment by murarth** [comment]
`recip` can also be made to produce a zero denominator. Should that be changed to panic?

**Comment by cuviper** [comment]
Yeah, since `div` will panic on zero denominator, `recip` probably should too.

I don't really like that `Ratio::new_raw` is a public function, allowing anyone to create a zero-denominator `Ratio`.  That enables nonsense like 0/0 comparing equal to anything, so it's not even safe for `Ord`.  But even if we hid `new_raw`, `new`+`recip` shouldn't sidestep it.

**Comment by murarth** [comment]
Perhaps `Ratio::new_raw` makes more sense as an `unsafe` function, with documentation noting that the caller should ensure that the denominator is non-zero.
