### ISSUE TITLE
Document PrimInt

### ISSUE THREAD

**Issue by gnzlbg** [rust-num/num#140]
It took me a bit to realize that PrimInt is the trait that provides the bit manipulation operations on primitive types (nothing more, nothing less). The methods are documented but the Trait itself is not documented.

**Comment by cuviper** [comment]
`PrimInt` corresponds to the unique methods of rust's old `Int` trait (removed in rust-lang/rust@eeb94886adccb3f13003f92f117115d17846ce1f), with the methods that were already covered in traits like `Zero` and `One` now added by inheritance.  Because of the broad inherited traits, it's not really "just" a bit-twiddling trait though, so it should be documented as being a generic primitives trait.

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-traits#11
