### ISSUE TITLE
Implement std::num::One

### ISSUE THREAD

**Issue by fenhl** [rust-num/num#197]
The trait `std::num::One` is not implemented for `BigUint`. This makes iteration over a range of `BigUint`s impossible.

**Comment by cuviper** [comment]
We can't because `std::num::One` is not stable (rust-lang/rust#27739), and neither is `std::iter::Step` (rust-lang/rust#27741) which is required for `std::ops::Range` to implement `Iterator`.

This is exactly why `num`'s own [`One`](http://rust-num.github.io/num/num_traits/identities/trait.One.html) and [`range`](http://rust-num.github.io/num/num_iter/fn.range.html) exist.
