### ISSUE TITLE
BigUint compares poorly with Python-3's int 

### ISSUE THREAD

**Issue by saurvs** [rust-num/num#200]
Timing trivial implementations, in Rust 1.9 and Python 3, for generating the Fibonacci series shows a stark difference in performance.

```rust
extern crate num;

use num::*;

fn fib(n: u64) -> BigUint {
    if n == 1 || n == 2 {
        return BigUint::one();
    }

    let mut a = BigUint::one();
    let mut b = BigUint::one();

    for _ in 0..n {
        b = b + &a;
        a = &b - &a;
    }

    b
}

fn main() {
    fib(100000);
}
```

```bash
$ cargo build --release
$ time ./target/debug/fib

real	0m28.996s
user	0m27.539s
sys	    0m0.097s
```

```python
def fib(n):
    if n == 1 or n == 2:
        return 1
    a = 1
    b = 1
    for _ in range(n):
        b = b + a
        a = b - a
    return b

fib(100000)
```

```bash
$ time python3 fib.py

real	0m0.466s
user	0m0.444s
sys	    0m0.012s
```

**Comment by bluss** [comment]
Can you please repeat that using optimizations? Run the binary in target/release

**Comment by ssrvv** [comment]
```bash
$ time ./target/release/fib

real	0m0.633s
user	0m0.612s
sys     0m0.005s
```

Okay, still slower than Python.

Timing both programs with `fib(1000000)` (extra zero) gave:

```bash
$ time ./target/release/fib

real	1m7.219s
user	1m2.668s
sys     0m0.277s
```

```bash
$ time python3 fib.py

real	0m40.180s
user	0m38.090s
sys     0m0.143s
```

**Comment by cuviper** [comment]
Just to be clear, this isn't a performance win for the Python language itself.  Most of its time here is spent in `x_add` and `x_sub`, which are written in C.  The top 5 profiled for me are:

```
   51.09%  python3  libpython3.5m.so.1.0  [.] x_sub
    46.50%  python3  libpython3.5m.so.1.0  [.] x_add
     0.33%  python3  libpython3.5m.so.1.0  [.] PyEval_EvalFrameEx
     0.13%  python3  libc-2.23.so          [.] _int_malloc
     0.11%  python3  libpython3.5m.so.1.0  [.] _PyObject_Alloc.isra.0
```

The top 5 I get for your Rust version are:

```
    58.09%  fib      fib                 [.] _$LT$BigUint$u20$as$u20$std..ops..Sub$LT$$RF$$u27$a$u20$BigUint$GT$$GT$::sub::h141140a7bc3b84fa
    36.76%  fib      fib                 [.] _$LT$BigUint$u20$as$u20$std..ops..Add$LT$$RF$$u27$a$u20$BigUint$GT$$GT$::add::h4276a18013e52fc5
     4.44%  fib      libc-2.23.so        [.] __memcpy_sse2_unaligned
     0.05%  fib      fib                 [.] sdallocx
     0.04%  fib      fib                 [.] arena_run_dalloc
```

So `Sub` is disproportionately  higher -- might be something to optimize there.

At least part of it is that you're subtracting by reference.  We clone the left side so it's a `val - ref` to then subtract in place, which is why `memcpy` shows in the profile.  Perhaps we should separate this implementation from the in-place version to avoid cloning, and just write the result in a brand new buffer.

It's also possible to avoid subtraction altogether for both languages -- call these "fib2":

```python
    for _ in range(n):
        a, b = b, b + a
```

```rust
    for _ in 0..n {
        a = a + &b;
        std::mem::swap(&mut a, &mut b);
    }
```

My results for each `fib(1000000)`:

Program | Time elapsed (s) | Max resident (KB)
--- | --- | ---
fib.py | 24.54 | 8740
fib.rs | 39.58 | 3316
fib2.py | 10.15 | 8796
fib2.rs | 14.66 | 2760

**Comment by ssrvv** [comment]
Thank you for the clarification. I just wanted point out that even in an interpreted language, which in this example lets C do the heavy lifting as you said, still beats out plain Rust, and it's apparent even in the optimized version you gave. I (perhaps naively) expected otherwise.

**Comment by cuviper** [comment]
It's ok to point out -- we do have room for improvement.  I've been playing with this a bit here and already managed to close the gap considerably, just by splitting a few loops to reduce branching.  I'll clean this up and post a PR later, but just to tease, right now I'm down to 28.07s for fib and 11.69s for fib2.

I also found the cpython implementation interesting in that they use only 30 out of 32 bits on 64-bit platforms, or 15 out of 16 bits on 32-bit platforms.  This lets them extract carry bits directly without promoting to a larger integer type, and even multiplication always fits in the native register size.  (It's 30 instead of 31 because apparently their `pow` implementation needs a multiple of 5.)  It would be very invasive for us to switch to a similar scheme, but it's interesting nonetheless.

**Comment by koverstreet** [comment]
One idea I had awhile ago is that it would be _really_ nice if code could tell the optimizer about things it could rewrite.

In your original version with the subtract, you have
a = b - a

That's not being done in place because we can only do subtracts in place on the first argument, not the second (we'd have to have a subtract method that took the first argument by reference and the second by value, and I don't _think_ the compiler allows that).

We could do it in place if we rewrote it like so:
a = -a
a += b

The optimizer does rewriting like this all the time, what we would need is a way for a library to provide the optimizer rules for its methods. A _lot_ of bignum code would benefit from this.

cuviper - that 30 out of 32 bits is a neat trick, apparently gmp can work in a mode like that too. Maybe I'll dig out my patches to modularize the low level ops (for inline asm), would probably be easy to add version of the low level ops that used that trick.

**Comment by cuviper** [comment]
> we'd have to have a subtract method that took the first argument by reference and the second by value, and I don't think the compiler allows that

Sure it allows that: `impl<'a> Sub<BigUint> for &'a BigUint {...}` -- in fact we already write forwarding rules for this, but we could give it a special implementation.

> We could do it in place if we rewrote it like so:
> a = -a
> a += b

`BigUint` has a panicking `Neg`.  I'm not sure why we have it at all, although we could let just 0 negate.  Anything else can't be represented unsigned.

We do play games on the `BigInt` side to arrange subtraction as best we can -- see the `bigint_sub` macro.  This could also benefit if there were an unsigned `ref-val` optimization.

---

FWIW I committed my optimizations in #201.  That gets the original code with a million iterations down to about 28s, compared to python's 24s.  The profiles are more similar now too:

```
  57.04%  fib.py   libpython3.5m.so.1.0  [.] x_sub
  41.71%  fib.py   libpython3.5m.so.1.0  [.] x_add
   0.29%  fib.py   libpython3.5m.so.1.0  [.] PyEval_EvalFrameEx
   0.11%  fib.py   libc-2.23.so          [.] _int_malloc
   0.10%  fib.py   libpython3.5m.so.1.0  [.] _PyObject_Alloc.isra.0
```

```
  51.99%  fib      fib                 [.] _$LT$BigUint$u20$as$u20$std..ops..Sub$LT$$RF$$u27$a$u20$BigUint$GT$$GT$::sub::h851f516bee46c526
  41.15%  fib      fib                 [.] _$LT$BigUint$u20$as$u20$std..ops..Add$LT$$RF$$u27$a$u20$BigUint$GT$$GT$::add::h46f6fd3ab7ed91a5
   6.21%  fib      libc-2.23.so        [.] __memcpy_sse2_unaligned
   0.08%  fib      fib                 [.] sdallocx
   0.05%  fib      libpthread-2.23.so  [.] pthread_mutex_unlock
```

(again that memcpy is attributed to the cloning before `Sub`)

Comparing the hot loop in annotated assembly, here's python `x_sub`:

```
  2.96 │99ce0:   mov    0x18(%r13,%rdx,4),%eax
 19.72 │99ce5:   sub    0x18(%r15,%rdx,4),%eax
  0.30 │99cea:   sub    %ecx,%eax
  9.28 │99cec:   mov    %eax,%ecx
  5.51 │99cee:   shr    $0x1e,%eax
 21.01 │99cf1:   and    $0x3fffffff,%ecx
  5.45 │99cf7:   and    $0x1,%eax
 13.84 │99cfa:   mov    %ecx,0x18(%r12,%rdx,4)
  2.90 │99cff:   add    $0x1,%rdx
  4.99 │99d03:   mov    %eax,%ecx
 13.90 │99d05:   cmp    %rdx,%rbp
  0.03 │99d08: ↓ jne    99ce0 <PyLong_FromLong@@Base+0xc70>
```

(perf is confused about function names and the `jne` arrow...)

Python `x_add`:

```
  0.71 │97ec8:   mov    0x18(%r13,%rcx,4),%edi
  4.73 │97ecd:   add    0x18(%rbp,%rcx,4),%edi
 24.53 │97ed1:   add    %edi,%edx
  4.76 │97ed3:   mov    %edx,%edi
  3.99 │97ed5:   shr    $0x1e,%edx
 11.70 │97ed8:   and    $0x3fffffff,%edi
 24.69 │97ede:   mov    %edi,0x18(%rax,%rcx,4)
  0.25 │97ee2:   add    $0x1,%rcx
  0.03 │97ee6:   cmp    %rcx,%rbx
 24.42 │97ee9: ↓ jne    97ec8 <_PyLong_New@@Base+0xca8>
```

Now Rust's `Sub::sub`:

```
 19.72 │58c0:   test   %rax,%rax
  0.03 │58c3: ↓ je     58ef <_$LT$BigUint$u20$as$u20$std..ops..Sub$LT$$RF$$u27$a$u20$BigUint$GT$$GT$::sub::h851f516bee46c526+0x9f>
  0.07 │58c5:   mov    (%rcx),%ebp
  0.45 │58c7:   or     %r13,%rbp
 20.09 │58ca:   mov    (%rdx),%r8d
  0.02 │58cd:   add    $0x4,%rdx
  0.12 │58d1:   sub    %r8,%rbp
  0.43 │58d4:   mov    %ebx,%ebx
 19.87 │58d6:   sub    %rbx,%rbp
  0.24 │58d9:   mov    %ebp,(%rcx)
       │58db:   shr    $0x20,%rbp
 18.66 │58df:   sete   %bl
 19.69 │58e2:   movzbl %bl,%ebx
  0.03 │58e5:   lea    0x4(%rcx),%rcx
       │58e9:   add    $0xfffffffffffffffc,%rax
  0.46 │58ed: ↑ jne    58c0 <_$LT$BigUint$u20$as$u20$std..ops..Sub$LT$$RF$$u27$a$u20$BigUint$GT$$GT$::sub::h851f516bee46c526+0x70>
```

Rust's `Add::add`:

```
  0.24 │5750:   test   %rsi,%rsi
  0.56 │5753: ↓ je     5775 <_$LT$BigUint$u20$as$u20$std..ops..Add$LT$$RF$$u27$a$u20$BigUint$GT$$GT$::add::h46f6fd3ab7ed91a5+0xe5>
  1.24 │5755:   mov    (%rcx),%edi
 23.71 │5757:   mov    (%rdx),%ebp
  0.22 │5759:   add    $0x4,%rdx
  0.46 │575d:   mov    %ebx,%ebx
  1.22 │575f:   add    %rdi,%rbx
 23.56 │5762:   add    %rbp,%rbx
 23.55 │5765:   mov    %ebx,(%rcx)
  0.25 │5767:   shr    $0x20,%rbx
  0.60 │576b:   lea    0x4(%rcx),%rcx
  0.93 │576f:   add    $0xfffffffffffffffc,%rsi
 23.33 │5773: ↑ jne    5750 <_$LT$BigUint$u20$as$u20$std..ops..Add$LT$$RF$$u27$a$u20$BigUint$GT$$GT$::add::h46f6fd3ab7ed91a5+0xc0>
```

I notice that the initial `test; je` exit in the Rust versions are useless for the loops, since we only take the back edge when it's known non-zero already.  Other than that, they aren't *terribly* different from the python versions beyond the bit tricks already noted.

Note also that we're comparing different optimizers, since my python was compiled with GCC 6.1 versus Rust's LLVM ~3.8.  I'd be interested to see how python does when compiled with clang, so it's a more direct comparison.

**Comment by koverstreet** [comment]
I knew I had something wrong there... I might add that forward to BigUint subtract then.

The optimizer pattern thing would be really useful for accumulate operations though - multiplies can't be done in place, but if you have an expression like:
acc += x * y;

that can be.

I'm making progress on porting my old asm/BigDigit as usize patches... the main hassle is just all the test code that assumes BigDigit is u32. I'm thinking we ought to get those patches in (perhaps minus asm for now), just to keep the code from growing more such assumptions.

**Comment by cuviper** [comment]
The immediate improvements in #201 and #205 are now published, and I think @koverstreet has a few more changes on the way.  In general, we can treat this as on ongoing task, so this bug doesn't need to remain open.
