### ISSUE TITLE
Migrate from Homu to Aelita

### ISSUE THREAD

**Issue by hauleth** [rust-num/num#230]
@homu (configuration site) seems broken from some time and I believe that this isn't gonna to change soon.

Instead I suggests that we should move to @aelita-mergebot instead. It is FOSS alternative to @homu written in Rust (https://github.com/AelitaBot/aelita).

**Comment by cuviper** [comment]
Yes, homu.io is broken, but the bot itself is working OK for now.  I hesitate changing this since Aelita calls itself "very experimental" and "production-esque".

FWIW, the rust-community team is planning to offer a forked homu as bors.io:
https://github.com/rust-community/team/issues/41
https://github.com/rust-community/bors
(although that initial momentum looks gone now...)

**Comment by cuviper** [comment]
It seems Aelita is [now deprecated](https://users.rust-lang.org/t/aelitabot-xyz-get-bors-like-commit-checking-on-your-own-github-repo/6969/5) in favor of [bors-ng](https://bors-ng.github.io/).  But it sounds like there are still a few kinks to work out, so we can stick with @homu while it still works.

**Comment by notriddle** [comment]
Most of the "kinks" that would affect rust-num have been worked out.

**Comment by notriddle** [comment]
This issue should probably be closed, now that rust-num is using bors-ng. 😄

**Comment by cuviper** [comment]
Indeed, thanks! :)
