### ISSUE TITLE
Using Complex in a hashset?

### ISSUE THREAD

**Issue by amstocker** [rust-num/num#245]
Hi All,

I am trying to use complex numbers (rustc v1.13.0, num v0.1.36, num-complex v0.1.35) in a HashSet, for example:

```rust
extern crate num;

use std::collections::HashSet;
use num::complex::*;

fn main() {
    let mut set = HashSet::new();
    let z = Complex::new(1, 1);
    set.insert(z);
}
```

and I get the following error;

```
error[E0277]: the trait bound `num::Complex<{integer}>: std::cmp::Eq` is not satisfied
 --> src/main.rs:8:19
  |
8 |     let mut set = HashSet::new();
  |                   ^^^^^^^^^^^^ trait `num::Complex<{integer}>: std::cmp::Eq` not satisfied
  |
  = note: required by `<std::collections::HashSet<T>>::new`

error[E0277]: the trait bound `num::Complex<{integer}>: std::cmp::Eq` is not satisfied
  --> src/main.rs:10:9
   |
10 |     set.insert(z);
   |         ^^^^^^ trait `num::Complex<{integer}>: std::cmp::Eq` not satisfied
```

I'm confused because in the documentation is says PartialEq is implemented for complex numbers, and doesn't that mean Eq is also implemented?  Any help here would be greatly appreciated!  Thanks.

**Comment by cuviper** [comment]
> PartialEq is implemented for complex numbers, and doesn't that mean Eq is also implemented?

No, `PartialEq` is a sort of *weak* equality, whereas [`Eq`](https://doc.rust-lang.org/stable/std/cmp/trait.Eq.html) requires that it is reflexive, symmetric, and transitive.  So `Eq` implies `PartialEq`, but not the other way around.  Notably, floats are not `Eq` because NaN is always unequal, even to itself, so if you put a NaN in a `HashSet`, you'd never be able to find it again! :smile: 

But I think we could support `Eq` just fine for integers, or any other base type that supports `Eq`.  It was probably just an oversight to not have this, since `Complex` is usually used with floats.

**Comment by amstocker** [comment]
@cuviper Cool!  Thanks for explaining the distinction between the two.  I was using complex numbers to solve http://adventofcode.com/2016/day/1 so it's not exactly a piece of critical software ;).  Thanks for your help.
