### ISSUE TITLE
Integer should be in num_traits

### ISSUE THREAD

**Issue by nwin** [rust-num/num#254]
As `Float` is in `num_traits`, `Integer` should be there as well.

What do you think? I would file a PR if you agree.

**Comment by hauleth** [comment]
I also think so but this would be breaking change. However I think that now is the time to introduce such changes, what do you think @cuviper

**Comment by cuviper** [comment]
It might be possible to move it to num-traits and re-export from num-integer for compatibility.

It's not quite the same as Float though, since Integer is also implemented by BigUint and BigInt.  Float requires Copy, which in practice makes it more similar to PrimInt.

**Comment by nwin** [comment]
Why is that so? Shouldn’t the traits be more-or-less equivalent? Since `Copy` can’t be implemented for  `Big(U)Int`,  `Float` shouldn’t require it as well.

Re-exporting + deprecating in `num-integer` sounds fine.

**Comment by cuviper** [comment]
In general, the answer to any question why `num` is weird is that's it's legacy.  This library originated from all the parts of `std::num` that were ejected before Rust 1.0 for being inconsistent, not well thought out, or otherwise not wanted to be maintained as-is in the standard library forever.  But people still want this functionality, so `num` continues to exist.

In this case, if it were symmetrical, there would probably be a `PrimFloat` filling the same role as `PrimInt`, and `Float` would be more like `Integer` without `Copy`.  I don't know if there's any realistic need for anyone to implement a non-primitive `Float` though.

We can't just remove `Float: Copy`, as that would break anyone using `T: Float` and expecting it to be able to copy.  The transitive trait requirements are part of the API contract.

**Comment by cuviper** [comment]
I think the status quo will remain for now.  FYI, these now have separate repos:
https://github.com/rust-num/num-integer
https://github.com/rust-num/num-traits
