### ISSUE TITLE
Prepare to breaking changes

### ISSUE THREAD

**Issue by hauleth** [rust-num/num#261]
I think that as we got custom `derive` support in stable we should think about freezing `0.1.x` branch and think about jump to `0.2` with breaking changes.

cc @cuviper

**Comment by cuviper** [comment]
Did you see #257?  I think due to that break out of our control, we could go ahead and raise our base to Rust 1.8 without breaking things any further, and thus get access to some nice things like `OpAssign` traits.

If we want custom derive, we have to jump all the way to 1.15.  Maybe that's justifiable, but I'm also looking towards `i128`/`u128` stabilizing sometime soon, and that's a much stronger fit for `num`.  However, that might also be possible to just add behind a simple `num128` feature.

We can still stabilize `num-derive` on 1.15+ regardless, as that was nightly-only until now.

**Comment by cuviper** [comment]
I've opened a `next` branch and #302 to start it.

**Comment by cuviper** [comment]
Semver bumps should now be considered on each crate's separate repo.

cc #354 #356
