### ISSUE TITLE
Consider simplifying identity traits

### ISSUE THREAD

**Issue by nox** [rust-num/num#295]
In Servo, I have a use for a `Zero` trait without an `Add` bound. Could we consider removing the bound? There is currently no such trait anywhere in Rust land, and the deprecated `std::num::Zero` trait doesn't include that bound.

**Comment by cuviper** [comment]
FWIW, since `num` came from `std::num` in the first place, [`std::num::Zero` did have `Add`](https://doc.rust-lang.org/0.12.0/std/num/trait.Zero.html) before.

This would be a breaking change for us, since anyone using `T: Zero` now can implicitly use `Add` too.

Can you point to a specific case where you need `Zero` without `Add`?  Presumably this would be something not just where `Add` isn't needed, but a type that **can't** implement `Add`.

**Comment by cuviper** [comment]
If you have more information about why you need this, please reopen it on the separate num-traits repo.
https://github.com/rust-num/num-traits/issues
