### ISSUE TITLE
Speed-up integer multiplication by implementing the Toom-3 algorithm

### ISSUE THREAD

**Issue by kompass** [rust-num/num#326]
Hi !

I am implementing the Toom-3 algorithm to speed-up the BigUint an BigInt multiplications. We get the multiplication of integers in almost all the algorithms, so it may accelerate much of the functionality of the library.

What do you think ? I might need some help to optimize everything. What is the best way to compare performances ? The basic `cargo bench` doesn't say enough.

**Comment by cuviper** [comment]
We already use Karatsuba, which is basically Toom-2 -- cc @koverstreet who added that.  If you want to go up to Toom-3, we'll need to make sure the constant factors in the more complex algorithm aren't excessive, or try to use a hybrid that chooses different paths depending on size.  (just like we already fall back to long multiplication for small inputs.)

In the root crate, `cargo bench --bench bigint multiply` are the benchmarks we have now.  If those aren't enough in your opinion, feel free to add more.  I suggest you organize your commits so new benchmarks are added before any algorithmic changes, so we can properly compare before and after.

**Comment by koverstreet** [comment]
Karatsuba is faster than Toom-3 for medium sized numbers, so Toom-3 definitely wouldn't be replacing Karatsuba - you'd pick based on the size of the numbers in mac3().

mac3() already does this to switch between Karatsuba and long multiplication, but it's buried in there with a magic number for the constant. If we add another multiplication algorithm, the dispatching and that constant should be factored out, and ideally we'd be able to pick those constants by benchmarking at compile time.

However, before you rush to add Toom-3 - the reason I never did is because I saw a paper that claimed (haven't been able to find it since, alas...) that a good streamlined implementation of FFT multiplication beats Toom-3 (not full blown Schönhage–Strassen). Alas, implementing FFT multiplication is a bit beyond my math skills.

**Comment by kompass** [comment]
Yes I had planned to use Toom-3 only for very large numbers. It will be necessary to measure from what size Toom-3 is faster. I'm inspired by how gmp works: https://gmplib.org/manual/Multiplication-Algorithms.html#Multiplication-Algorithms

**Comment by kompass** [comment]
For the benchmark, I wanted to see the time spent on kernel mode, to decrease as much as possible the time lost in memory allocation, the linux command `time` and a custom prototyping program will do the job.

**Comment by kompass** [comment]
#328

**Comment by notriddle** [comment]
Close this issue?

**Comment by cuviper** [comment]
Yep, thanks!
