### ISSUE TITLE
assign traits not visible on BigUint

### ISSUE THREAD

**Issue by Silur** [rust-num/num#346]
following example:

```rust
extern crate num_bigint;
use num_bigint::BigUint;
use std::ops::{AddAssign, SubAssign};
// tried also num_traits::NumAssignOps::{AddAssign, SubAssign}, same issue

fn main() {
  let mut a = BigUint::from_bytes_be(b"A");
  a.add_assign(1);
  a.sub_assign(1);
}
```
returns with `no method named 'add' found for type 'num_bigint::BigUint' in the current scope`, `no method named 'sub' found for type 'num_bigint::BigUint' in the current scope`
Same happens for every other documented trait (OpAssigns etc);

calling with `num_traits::NumAssignOps::AddAssign::add_assign(a, b)` results with 'the trait is not implemented by type BigUint` however it's stated in the documentation.

**Non-assign ops work fine.**
Environment:
AArch64 3.10 kernel
rustc 1.22.1 (05e2e1c41 2017-11-22)
cargo 0.23.0 (61fa02415 2017-11-22)
num crate 0.1.40

**Comment by cuviper** [comment]
For `Add`, I believe it's a type inference problem for the integer literal.  `BigUint` implements `Add` for all unsigned primitive integers, but when rustc doesn't know which type to use, it chooses `i32`.  Making it explicit like `add(1u8)` should work.

For `AddAssign`, it will have the same problem, but I also haven't published a new version since that was merged.  I should do that...

**Comment by cuviper** [comment]
num and num-bigint are now updated to 0.1.41.  Please let me know if you see any issues!

**Comment by cuviper** [comment]
I believe this is complete.  If not, please open a new issue on [num-bigint](https://github.com/rust-num/num-bigint)
