### ISSUE TITLE
Surprising behavior when right-shifting a negative BigInt

### ISSUE THREAD

**Issue by mhogrefe** [rust-num/num#347]
Right-shifting an primitive integer in Rust (and most other languages AFAIK) is equivalent to dividing by a power of 2 and rounding towards -∞. But right-shifting a BigInt rounds towards 0 instead.

You can see the difference by pasting the following into [https://play.rust-lang.org/](https://play.rust-lang.org/):
```
extern crate num;

fn main() {
    println!("-1 >> 1 == {} (primitive)", -1 >> 1);
    println!("-1 >> 1 == {} (BigInt)", num::BigInt::from(-1) >> 1);
}
```
This prints
```
-1 >> 1 == -1 (primitive)
-1 >> 1 == 0 (BigInt)
```

If this behavior is intentional it should probably be documented and unit-tested.

**Comment by cuviper** [comment]
That's interesting. This behavior is neither an arithmetic nor logical right shift, but sort of a weird hybrid. I don't think this was intentional, just a casual side effect of shifting the internal `BigUint` while preserving the sign.

I worry slightly that changing this would be a breaking change, but I think we can call it just a bug fix. The current behavior is unprecedented in other languages AFAIK, and matching the primitive behavior would be much more useful.

**Comment by cuviper** [comment]
Well sure, GMP implements every conceivable variation. :)

I don't know a way to search for this.  @rust-lang has a "crater" tool that compiles every published crate and some more on GitHub, but this isn't generally available for use.  I suppose we could just poll the users forum and /r/rust.

Generally speaking though, I think we want to match primitive operators in all aspects (except overflow).  That's applying the principle of least surprise, and we could implement alternate forms as other methods if we want to generalize choices.

**Comment by tspiteri** [comment]
GMP does have a definition `#define mpz_div_2exp	mpz_fdiv_q_2exp` in *gmp.h*. It is undocumented and I think it's only there for some compatibility with GMP 1, back when that was the only available variation.

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-bigint#1
