### ISSUE TITLE
Add nightly feature, const fn constructors

### ISSUE THREAD

**Issue by joshlf** [rust-num/num#359]
I've been programming with `num_bigint` and `num_rational` recently, and found it very cumbersome to create constants in a way that is efficient at runtime. `const fn`s would help this a lot (but would of course need to be feature-gated so that they're only used on nightly).

**Comment by cuviper** [comment]
Does `Vec` have any const constructors yet?  I don't see how we can do `BigUint` otherwise...

For `Ratio`, I'm not sure it's possible -- it seems like the constructor would have to be conditional on the constness of methods in the underlying generic `T`, unless we hard-coded it for specific types only.  But `Ratio::new_raw` is as simple as it gets -- is it really a problem for you to be "efficient at runtime"?

I guess in both cases, my question is "*can* we do it at all?" before we evaluate the possible benefit.

**Comment by joshlf** [comment]
Yeah, those are fair concerns. I thought about `Vec` a bit, and I realized that it will probably never be able to have a const constructor because I can't see a way that having static variables which contain pointers to the heap could work.

That said, have you considered using [smallvec](https://crates.io/crates/smallvec) instead of `Vec` for the backing store for integers? It wouldn't solve the const problem, but it'd at least make initializing small numbers a lot cheaper than if allocation was always required.

**Comment by cuviper** [comment]
I'm not sure that smallvec will keep the same stability regarding rustc compatibility, as I prefer, but we could also roll our own with the limited subset of Vec functionality we actually use.

If you want to discuss that further, let's take it to the new rust-num/num-bigint repo.

**Comment by joshlf** [comment]
I tried patching num-bigint myself to test, and most things got slower (unsurprising), but even cloning didn't get much faster, which I expected it would because of the lack of allocation. In any case, it seems like this wouldn't help as much as I'd hoped and would generally slow things down, so unless there are other reasons I'm missing, it's probably not worth the effort.

**Comment by cuviper** [comment]
Ok, thanks for trying it!

**Comment by joshlf** [comment]
np!
