### ISSUE TITLE
trait rand::distributions::range::SampleRange for Integer

### ISSUE THREAD

**Issue by zadlg** [rust-num/num#363]
It could be nice if Integer requires the _rand::distributions::range::SampleRange_ trait, in order to use things like
```rust
 rand::os::OsRng::new().unwrap().gen_range(start, end)
```
with start and end _num::BigInt_ for example.

I'm trying to implement the Fermat primality test with generic type, therefore it needs to generate a random number in specific range.

**Comment by cuviper** [comment]
You can always use `Integer + SampleRange` in your own code.

However, external types like `BigInt` *can't* implement `SampleRange`, because it's intertwined with the private internals of `rand::distributions::range::Range`.  `Range::new` calls `SampleRange::construct_range` to fill in the private fields, and there's no way for an outsider to construct a `Range` otherwise.

This is basically the reason why [`RandBigInt`](https://docs.rs/num-bigint/0.1.43/num_bigint/trait.RandBigInt.html) exists.

**Comment by zadlg** [comment]
Late, but thank you for your answer. :) I use `RandBigInt` now, it works perfectly.!
