### ISSUE TITLE
[question] Why does `CheckedAdd` accept self by-ref

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-num/num#387]
Why do `Checked{Add,Sub,Mul,Div}` accept `self` and `rhs` by-ref and not by-value? This differs from std's `Add`, `Sub`, `Mul`, `Div`. Also implementations need to deref `self`/`rhs` and that looks strange: https://rust-num.github.io/num/src/num_traits/ops/checked.rs.html#14

**Comment by cuviper** [comment]
> Why do `Checked{Add,Sub,Mul,Div}` accept `self` and `rhs` by-ref and not by-value?

Because these traits are for more that just the primitive types. Allocated types like `BigInt` can benefit from doing operations by reference rather than passing an owned value every time.

> This differs from std's `Add`, `Sub`, `Mul`, `Div`.

Each primitive type in `std` actually has 4 implementations of each of these traits -- for example:

- `impl Add<i32> for i32`
- `impl<'_> Add<&'_ i32> for i32`
- `impl<'_> Add<i32> for &'_ i32`
- `impl<'_, '_> Add<&'_ i32> for &'_ i32`

We could emulate all of that in `CheckedAdd` too if we added an `RHS` type parameter and `Output` associated type, but I'm not sure it's worth the complexity.

> Also implementations need to deref `self`/`rhs` and that looks strange:

It might look strange, but when these are inlined and optimized, it should be harmless.

**Comment by WaffleLapkin** [comment]
I still think that it would be more clear to have 4 impls (`BigInt` can have only &/&), but now I understand the reasons for that design, thanks!
