### ISSUE TITLE
Decomposition of Float trait

### ISSUE THREAD

**Issue by JulianKnodt** [rust-num/num#396]
This is more of a question than an issue, so I hope that's alright.

I've been using the float trait extensively in order to make generic code, but looking at the trait it seems to be incredibly stiff in what it can be implemented for. That is, certain functions such `integer_decode` and `classify` restrict the trait to only be implemented for scalar floats. Most of the other functions though, can be generalized to vectors & matrices(i.e. sin or pow). Would it be useful to decompose the float trait into one that specific to scalars, and one that is more about the operations that can be performed on floats, or should that be done on the application level or another library instead?

If this is the place to do it, I can do the work for it, but just wanted to know if it'd be alright.

Edit: While the real trait satisfies a lot of these criteria, the `is_sign_positive` function is not well defined over a vector so it would essentially be reduced to only functions that return self

**Comment by cuviper** [comment]
No worries, the question is fine.

I think I don't want to add more traits in this area though. There are already three, `Float`, `FloatCore`, and `Real`, plus the related `FloatConst`. I avoid breaking semver updates in `num-traits` since it's often a public dependency for interoperability among crates, which means changing the composition of those existing traits is not really on the table. A new addition would be similarly API-locked as soon as we add it.

So I think it would be better for you to explore this independently.

**Comment by JulianKnodt** [comment]
Ah ok, thanks for the explanation.

I was thinking there might be some way to decompose the trait while retaining backwards compatibility, but I've not had a ton of experience with public facing APIs so that might be impossible.

Thanks for your response and work, I'll continue to look into this elsewhere!

**Comment by cuviper** [comment]
> I was thinking there might be some way to decompose the trait while retaining backwards compatibility, but I've not had a ton of experience with public facing APIs so that might be impossible.

It's not too difficult to keep compatibility for those using your trait, but it's harder not to affect third parties who are implementing your trait.
