### ISSUE TITLE
Add methods to all constants from 2 to 9

### ISSUE THREAD

**Issue by elsuizo** [rust-num/num#399]
Hi!!! i use this package a lot and and very often I have to write code like:

```rust
let one = T::one();
let two = one + one;
```
could be nice have a `T::two()` , `T::three()` ... `T::nine()`

Regards

**Comment by cuviper** [comment]
Rather than enumerating all "interesting" values in methods, I'd recommend using `FromPrimitive` or `TryFrom`.

**Comment by elsuizo** [comment]
But how do you do it if you don't know in advance if it will be an integer or a float?

**Comment by cuviper** [comment]
Ah, I forgot `TryFrom` is not implemented for floating point yet.

With `T: FromPrimitive`, `T::from_u8(2)`/etc. should work for integers and floats alike. At the type level this can fail for `T = i8`, since `128u8` exceeds `i8::MAX`, so you'll have to `unwrap()` or `expect(msg)`. The optimizer should eliminate the failure path if you only use smaller constant values.

If you don't need `T = i8`, then with infallible `T: From<u8>`, `T::from(2u8)` will work for all other integer and float types.

**Comment by elsuizo** [comment]
yeah cool `T::from(2u8)` works i don't like the `unwrap` but never mind
