### ISSUE TITLE
Conversion between openssl::bn::BigNum and num::BigInt

### ISSUE THREAD

**Issue by Nurrl** [rust-num/num#410]
Hello,

I would need this implementation for one of my project to work with `openssl`'s BigNum implementation, would this be in scope for this crate ? Should I do a PR ?

Thanks

**Comment by cuviper** [comment]
I would rather not add a dependency on `openssl`. Is there anything about this conversion that needs private access to the `num-bigint` implementation? At a glance, I think you'd probably just use `BigNum::from_slice` and `to_vec`, as well as `BigInt::from_bytes_be` and `to_bytes_be`. I don't see a way for either crate to convert more "natively" than that.

**Comment by Nurrl** [comment]
Hi, thanks for your fast answer,
at first glance no, there is no need for the private `num::BigInt` implementation, it's just that it could come really handy to do a `num.try_into()?` rather than `BigNum::from_slice(&num.to_signed_bytes_be()?)?` which is a really ugly syntax IMHO.
Could this be introduced via a special feature in any way or this is a no go for such conversions to other crate's types to ever happen ?

**Comment by cuviper** [comment]
It's possible to do that with an optional dependency, enabled using cargo features, but managing a bunch of dependencies this way gets cumbersome, especially if they ever have semver-incompatible version updates. There's nothing special about `openssl`, when we could also do this for `gmp`, `rug`, and others. I'd rather make sure we have sufficient API to make these conversions _possible_, without trying to implement every instance.

> at first glance no, there is no need for the private `num::BigInt` implementation, it's just that it could come really handy to do a `num.try_into()?` rather than `BigNum::from_slice(&num.to_signed_bytes_be()?)?` which is a really ugly syntax IMHO.

You can always wrap that in your own function to get something like `to_ssl(&num)?`, or as your own extension trait if you really want to use method syntax.

But don't use the `_signed_` conversion here, because that uses 2's complement for negative values. `BigNum::from_slice` wants the unsigned magnitude, and then you can negate that or `set_negative` if needed.

**Comment by Nurrl** [comment]
Alright, I get that, I think I'll end up doing my own trait at some point, thanks for the advice(s), closing the issue.
