### ISSUE TITLE
Approximate equality for floats

### ISSUE THREAD

**Issue by amab8901** [rust-num/num#439]
Can u add approximate equality for floats?

**Comment by cuviper** [comment]
There is no universal answer for how to define what is "close enough" to be approximately equal, but there are already multiple crates exploring this space. The 2 biggest that I know of are [`approx`](https://crates.io/crates/approx) and [`float-cmp`](https://crates.io/crates/float-cmp). If the standard library ever adds such functionality, then we might add generic versions of that to `num`, but otherwise I think we'll leave it to others.
