### ISSUE TITLE
Rename `to_bigint` to `to_big_int`

### ISSUE THREAD

**Issue by gsingh93** [rust-num/num#50]
Since `BigInt` is made up of two different words, they should be separated with an underscore in methods like `to_bigint` and `to_biguint`.

**Comment by andylamp** [comment]
@gsingh93 I'd be severely against it. All frameworks have combined these two words -- besides BigDecimal, BigInteger and relevant class names are used as one word.

**Comment by mandeep** [comment]
Not that my opinion matters, but I agree with @andylamp that the method names should remain the same as they relate directly to the class names.

**Comment by gsingh93** [comment]
Why do we choose to go against the conventional Rust naming conventions in just this specific case? Because there's precedent in other language?

In Rust there's precedent for using snake case here. Look at the `BinaryHeap` struct for example. It's contained in a module called `binary_heap`, not `binaryheap`. We're diverging from common Rust practices with this naming convention.

**Comment by cuviper** [comment]
I agree that the general precedent in Rust is to convert `CamelCase` to `snake_case`.  But there's also a historical precedent here, since this implementation came from the Rust standard library in the first place! (pre-1.0)

I don't feel strongly either way, but to avoid breaks I'd favor the status quo.  We *could* change it in a future release bump, but there's no real benefit here, just a slight naming consistency.

**Comment by cuviper** [comment]
FYI, num-bigint is in its own repo now: https://github.com/rust-num/num-bigint

But honestly, I still don't feel motivated to make such a breaking change.
