### ISSUE TITLE
Allow access to data vector

### ISSUE THREAD

**Issue by dbrgn** [rust-num/num#57]
(Rust beginner here, so forgive me if this is already possible :))

Is there a way to access the `data` attribute? This would be useful to iterate over the digits (e.g. to calculate the digital sum of a `BigUint`).

**Comment by gsingh93** [comment]
The data attribute is made up of `BigDigit`s, which do not correspond directly with digits. If you need access to the underlying bytes, you can get the byte representation of the the `BigInt` with `to_bytes_le` and `to_bytes_be`. I think your best bet for iterating over digits is to either convert to a string and iterate over that, or use a standard mod by 10 then divide by 10 algorithm.

**Comment by dbrgn** [comment]
Thanks for your reply! So what exactly is a `BigDigit`?

Regarding to `to_bytes_le` and `to_bytes_be`, what do these bytes represent? Is it just an internal implementation detail or can it be useful?

For now, I used this snippet:

```rust
bigint.to_string().chars().fold(0, |a, b| a + b.to_digit(10).unwrap() as u16)
```

**Comment by gsingh93** [comment]
A `BigDigit` is a `u32`: http://doc.rust-lang.org/num/num/bigint/type.BigDigit.html

Essentially it's a less convenient version of `to_bytes_*`, which return `u8`s. They are very useful, but in your case what you're doing is probably the best way to do it.

But since we do allow access to the internal bytes of the number, this issue should be closed.
